name: CorNetMeSHProbeNet

model:
  hidden_size: 300
  n_layers: 2
  n_probes: 5
  dropout: 0.5
  emb_trainable: False

train:
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  batch_size: 40

predict:
  batch_size: 40

path: /p/realai/guangxu/2020xmtc/deep_data/EUR-Lex/models
